language: python
python:
  - 2.7

matrix:
  exclude:
   - python: 2.7
  include:
    - python: 2.7
      env: pack=newest
    - python: 2.7
      env: pack=old_mpl
    - python: 3.3
      env: pack=newest
# It seems there is no matplotlib in condas python 2.6 repos :-(
#    - python: 2.6
#      env: pack=old_mpl


notifications:
  email: false

# Setup anaconda
before_install:
  - travis/miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # The next couple lines fix a crash with multiprocessing on Travis
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  #  Update conda else if will result in a problem when conda updates the repos...
  - conda update --yes conda 
  # Install dependencies
  # No idea why a two step process is needed :-(
  - if [ ${pack} == "old_mpl" ]; then conda install --yes pip python=$TRAVIS_PYTHON_VERSION matplotlib=1.1.1 ; fi
  - if [ ${pack} == "old_mpl" ]; then conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose dateutil pandas statsmodels pil six; fi
  - if [ ${pack} == "newest" ]; then conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose dateutil pandas statsmodels six; fi
  - pip install python-coveralls
  - pip install brewer2mpl
  - pip install nose-cov
  - pip install husl
  - python setup.py install
  - export MATPLOTLIB_BACKEND=agg
  # List all conda and pip packages
  - conda list

# Run test
script:
  # only use the unittests under ggplot/tests/ and not the manual tests in tests/
  - nosetests ggplot --with-cov --cov ggplot --cov-config .coveragerc --logging-level=INFO

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
